### ISSUE TITLE
Inserção de tabela de alunos

### ISSUE THREAD

**Issue by bmarchete** [eddubr/uniararas-teste#1]
@eddubr Precisamos criar a tabela de clientes. Vou fazer o esqueleto e aguardo vc inserir alguns dados! 😄

**Comment by eddubr** [comment]
👍

**Comment by eddubr** [comment]
Beleza aguardamos o Léo cortar o cabelo :)

**Comment by bmarchete** [comment]
@eddubr Tirei sua zueira e completei a tabela. O commit está aqui 8ba706e4f62ab6043e5416402a0a77c22e959afb

**Comment by eddubr** [comment]
@bmarchete inserção efetuada
